# Generated by Django 2.2 on 2020-05-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDNI', models.CharField(max_length=20, verbose_name='identificación')),
                ('nombUser', models.CharField(max_length=200, null=True, verbose_name='Nombres')),
                ('apelUser', models.CharField(max_length=200, null=True, verbose_name='Apellidos')),
                ('profeUser', models.CharField(max_length=100, null=True, verbose_name='Profesión')),
                ('fotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='Foto de Perfil')),
                ('teleUser', models.CharField(max_length=20, verbose_name='Número de telefono')),
                ('geneUser', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default=' Otro', max_length=20, verbose_name='Genero')),
                ('adddata', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modiflat', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
            ],
            options={
                'verbose_name': 'Datos de Usuario',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabil', models.CharField(max_length=155)),
                ('DescHabil', models.TextField(max_length=2000, verbose_name='Decripción de la Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidades del Usuario',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcrHabil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('udtHabil', models.DateTimeField(auto_now=True)),
                ('idHabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Habilidades')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Nivel de Habilidad',
                'verbose_name_plural': 'Niveles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addUser', models.DateTimeField(auto_now_add=True, null=True)),
                ('udtUser', models.DateTimeField(auto_now=True)),
                ('estaRol', models.CharField(max_length=10)),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Identificador de Rol')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Roles de Usuario',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
