# Generated by Django 2.2 on 2020-05-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='fotoUser',
            field=models.ImageField(default='user.png', upload_to='perfiles/img', verbose_name='Foto de perfil'),
        ),
    ]
